name: servxpert_frontend
description: A Flutter application for ServXpert service provider registration.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Bold.ttf
          weight: 700
    - family: SansSerif
      fonts:
        - asset: assets/fonts/SansSerif-Regular.ttf
        - asset: assets/fonts/SansSerif-Bold.ttf
          weight: 700